import type { MemoryDump, WikiMemory } from '@equationalapplications/expo-llm-wiki'
import type { OkfFile } from '~/utilities/okfImport'

// Profile §7 id-comment grammar. The $ anchors per LINE — the m flag is
// load-bearing: without it this matches at most one id (end of file).
const EVENT_ID_COMMENT_PATTERN = /<!--\s*id:\s*(\S+)\s*-->\s*$/gm

/**
 * Explicit event ids present in the bundle's log.md as id comments.
 * Events whose parsed id is in this set carry profile-1 identity; events
 * outside it got a freshly generated id from parseOkfBundle and need the
 * tuple fallback.
 */
export function scanExplicitEventIds(files: readonly OkfFile[]): Set<string> {
  const ids = new Set<string>()
  for (const file of files) {
    if (file.path !== 'log.md' && !file.path.endsWith('/log.md')) continue
    for (const match of file.content.matchAll(EVENT_ID_COMMENT_PATTERN)) {
      ids.add(match[1])
    }
  }
  return ids
}

function utcDayKey(createdAt: number): string {
  return new Date(createdAt).toISOString().slice(0, 10)
}

function eventDedupeKey(event: { event_type: string; summary: string; created_at: number }): string {
  const escape = (s: string) => s.replace(/\\/g, '\\\\').replace(/\|/g, '\\|')
  return `${escape(event.event_type)}|${escape(event.summary)}|${utcDayKey(event.created_at)}`
}

export async function dedupeEventsAgainstExisting(
  wiki: WikiMemory,
  entityId: string,
  dump: MemoryDump,
  explicitEventIds: ReadonlySet<string>,
): Promise<MemoryDump> {
  const entity = dump.entities[entityId]
  if (!entity || entity.events.length === 0) return dump

  // Profile §7: an explicit id IS the event's identity — the events table's
  // INSERT OR IGNORE on the id primary key makes re-import a no-op, and two
  // distinct profile-1 events may legitimately share the tuple. Only events
  // whose id was regenerated by parseOkfBundle (legacy bundles, stripped
  // comments) need the tuple fallback.
  const needsTupleCheck = entity.events.some((event) => !explicitEventIds.has(event.id))
  if (!needsTupleCheck) return dump

  const existingDump = await wiki.exportDump([entityId])
  const existingEvents = existingDump.entities[entityId]?.events ?? []
  const existingKeys = new Set(existingEvents.map(eventDedupeKey))

  const dedupedEvents = entity.events.filter(
    (event) => explicitEventIds.has(event.id) || !existingKeys.has(eventDedupeKey(event)),
  )

  return {
    ...dump,
    entities: {
      ...dump.entities,
      [entityId]: {
        ...entity,
        events: dedupedEvents,
      },
    },
  }
}
