blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/equationalapplications/clanker/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Issue
    url: mailto:info@equationalapplications.com
    about: Report security vulnerabilities via email (see SECURITY.md)
