export const SYNONYM_MAP_BASE: Record<string, string[]> = {
  // Exercise & fitness
  run: ['jog', 'sprint', 'exercise'],
  jog: ['run', 'exercise'],
  sprint: ['run', 'dash'],
  workout: ['exercise', 'training', 'gym'],
  exercise: ['workout', 'training', 'fitness'],
  training: ['workout', 'exercise', 'practice'],
  gym: ['fitness', 'workout'],
  fitness: ['health', 'exercise', 'gym'],
  walk: ['stroll', 'hike'],
  stroll: ['walk'],
  hike: ['walk', 'trek'],
  trek: ['hike'],
  swim: ['swimming', 'exercise'],
  swimming: ['swim', 'exercise'],
  cycle: ['bike', 'cycling'],
  bike: ['cycle', 'cycling'],
  cycling: ['bike', 'cycle'],
  yoga: ['stretch', 'meditation', 'exercise'],
  stretch: ['yoga', 'flexibility'],
  lift: ['weightlift', 'strength'],
  weightlift: ['lift', 'strength training'],

  // Health & body
  health: ['wellness', 'fitness'],
  wellness: ['health', 'wellbeing'],
  wellbeing: ['wellness', 'health'],
  diet: ['nutrition', 'eating', 'food'],
  nutrition: ['diet', 'eating', 'food'],
  sleep: ['rest', 'nap'],
  rest: ['sleep', 'relax', 'break'],
  nap: ['sleep', 'rest'],
  pain: ['ache', 'hurt', 'discomfort'],
  ache: ['pain', 'hurt', 'sore'],
  hurt: ['pain', 'ache'],
  sore: ['ache', 'pain'],
  tired: ['fatigue', 'exhausted', 'sleepy'],
  fatigue: ['tired', 'exhausted'],
  exhausted: ['tired', 'fatigue'],
  sick: ['ill', 'unwell'],
  ill: ['sick', 'unwell'],
  doctor: ['physician', 'medical'],
  physician: ['doctor'],
  medicine: ['medication', 'drug', 'treatment'],
  medication: ['medicine', 'drug'],
  treatment: ['therapy', 'medicine'],
  therapy: ['treatment', 'counseling'],
  hospital: ['clinic', 'medical'],
  clinic: ['hospital', 'doctor'],
  weight: ['mass', 'pounds', 'kilograms'],

  // Relationships
  spouse: ['partner', 'husband', 'wife'],
  partner: ['spouse', 'significant other'],
  husband: ['spouse', 'partner'],
  wife: ['spouse', 'partner'],
  girlfriend: ['partner', 'significant other'],
  boyfriend: ['partner', 'significant other'],
  friend: ['buddy', 'pal', 'companion'],
  buddy: ['friend', 'pal'],
  pal: ['friend', 'buddy'],
  family: ['relatives', 'kin'],
  parent: ['mother', 'father', 'mom', 'dad'],
  mother: ['mom', 'parent'],
  father: ['dad', 'parent'],
  mom: ['mother', 'parent'],
  dad: ['father', 'parent'],
  sibling: ['brother', 'sister'],
  brother: ['sibling'],
  sister: ['sibling'],
  child: ['kid', 'son', 'daughter'],
  kid: ['child'],
  son: ['child', 'kid'],
  daughter: ['child', 'kid'],
  colleague: ['coworker', 'teammate'],
  coworker: ['colleague', 'teammate'],
  teammate: ['colleague', 'coworker'],
  boss: ['manager', 'supervisor', 'employer'],
  manager: ['boss', 'supervisor'],
  supervisor: ['boss', 'manager'],

  // Work & career
  job: ['work', 'career', 'occupation', 'profession'],
  work: ['job', 'career', 'employment'],
  career: ['job', 'profession', 'work'],
  occupation: ['job', 'profession'],
  profession: ['career', 'occupation'],
  employment: ['work', 'job'],
  office: ['workplace', 'work'],
  workplace: ['office', 'work'],
  meeting: ['appointment', 'conference', 'call'],
  appointment: ['meeting', 'schedule'],
  conference: ['meeting', 'summit'],
  project: ['task', 'assignment', 'initiative'],
  task: ['project', 'assignment', 'todo'],
  assignment: ['task', 'project'],
  deadline: ['due date', 'cutoff'],
  salary: ['income', 'pay', 'wage', 'earnings'],
  income: ['salary', 'earnings', 'revenue'],
  pay: ['salary', 'wage', 'income'],
  wage: ['salary', 'pay', 'income'],
  earnings: ['income', 'salary'],
  promotion: ['raise', 'advancement'],
  raise: ['promotion', 'salary increase'],
  retirement: ['pension', 'savings'],

  // Goals & plans
  goal: ['plan', 'aim', 'target', 'objective'],
  plan: ['goal', 'strategy', 'agenda'],
  aim: ['goal', 'target'],
  target: ['goal', 'aim', 'objective'],
  objective: ['goal', 'target', 'aim'],
  strategy: ['plan', 'approach'],
  priority: ['importance', 'focus'],
  focus: ['priority', 'attention'],
  progress: ['advancement', 'improvement'],
  improvement: ['progress', 'growth'],
  habit: ['routine', 'practice'],
  routine: ['habit', 'schedule'],
  milestone: ['achievement', 'goal'],
  achievement: ['milestone', 'accomplishment'],
  accomplishment: ['achievement', 'success'],

  // Emotions & mental health
  stress: ['anxiety', 'pressure', 'tension'],
  anxiety: ['stress', 'worry', 'nervousness'],
  worry: ['anxiety', 'concern', 'stress'],
  pressure: ['stress', 'tension'],
  tension: ['stress', 'pressure'],
  happy: ['joyful', 'content', 'cheerful', 'glad'],
  joyful: ['happy', 'cheerful'],
  content: ['happy', 'satisfied'],
  cheerful: ['happy', 'joyful'],
  glad: ['happy', 'pleased'],
  sad: ['unhappy', 'depressed', 'down'],
  unhappy: ['sad', 'miserable'],
  depressed: ['sad', 'down'],
  angry: ['frustrated', 'upset', 'annoyed'],
  frustrated: ['angry', 'annoyed', 'upset'],
  upset: ['angry', 'frustrated'],
  annoyed: ['frustrated', 'irritated'],
  excited: ['enthusiastic', 'eager'],
  enthusiastic: ['excited', 'eager'],
  eager: ['excited', 'enthusiastic'],
  motivation: ['drive', 'inspiration', 'enthusiasm'],
  drive: ['motivation', 'ambition'],
  inspiration: ['motivation', 'creativity'],
  overwhelmed: ['stressed', 'overloaded'],
  burnout: ['exhausted', 'overwhelmed'],
  meditation: ['mindfulness', 'relaxation'],
  mindfulness: ['meditation', 'awareness'],
  relaxation: ['rest', 'meditation'],

  // Finance
  money: ['finance', 'cash', 'funds'],
  finance: ['money', 'budget', 'funds'],
  budget: ['finance', 'spending', 'money'],
  cash: ['money', 'funds'],
  funds: ['money', 'cash'],
  savings: ['investment', 'money', 'retirement'],
  investment: ['savings', 'finance'],
  expense: ['cost', 'spending', 'bill'],
  cost: ['expense', 'price'],
  spending: ['expense', 'budget'],
  bill: ['expense', 'payment'],
  payment: ['bill', 'expense'],
  debt: ['loan', 'credit'],
  loan: ['debt', 'credit'],
  credit: ['debt', 'loan'],

  // Food & eating
  food: ['meal', 'diet', 'nutrition', 'eating'],
  meal: ['food', 'dinner', 'lunch', 'breakfast'],
  breakfast: ['meal', 'morning food'],
  lunch: ['meal', 'midday meal'],
  dinner: ['meal', 'supper'],
  supper: ['dinner', 'meal'],
  snack: ['food', 'bite'],
  drink: ['beverage', 'water', 'fluid'],
  beverage: ['drink'],
  coffee: ['caffeine', 'drink'],
  caffeine: ['coffee', 'energy'],
  alcohol: ['drink', 'beer', 'wine'],
  water: ['hydration', 'drink'],
  hydration: ['water', 'fluid'],

  // Schedule & time
  morning: ['early', 'dawn', 'am'],
  evening: ['night', 'afternoon', 'pm'],
  night: ['evening', 'bedtime'],
  bedtime: ['night', 'sleep'],
  daily: ['everyday', 'regular'],
  weekly: ['every week', 'regular'],
  monthly: ['every month', 'regular'],
  schedule: ['calendar', 'agenda', 'routine'],
  calendar: ['schedule', 'agenda'],
  agenda: ['schedule', 'plan'],
  reminder: ['alert', 'notification'],
  alert: ['reminder', 'notification'],
  vacation: ['holiday', 'trip', 'travel'],
  holiday: ['vacation', 'break'],
  trip: ['travel', 'vacation', 'journey'],
  travel: ['trip', 'journey', 'vacation'],
  journey: ['trip', 'travel'],
}