name: Production EAS Update

permissions:
    contents: read

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-main
    cancel-in-progress: true
jobs:
    publish-ota-update:
        runs-on: ubuntu-latest

        steps:
            - name: 🏗 Setup repo
              uses: actions/checkout@v6
              with:
                  ref: main

            - name: 🏗 Setup Node
              uses: actions/setup-node@v6
              with:
                  node-version: 22
                  cache: "npm"

            - name: 📦 Install dependencies
              run: npm ci

            - name: 🏗 Install EAS CLI
              run: npm install -g eas-cli

            - name: 🚀 Update Production with EAS
              run: npm run ota
              env:
                  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
