name: Production EAS Update

permissions:
    contents: read

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    publish-ota-update:
        runs-on: ubuntu-latest

        steps:
            - name: 🏗 Setup repo
              uses: actions/checkout@v6
              with:
                  ref: main

            - name: 🏗 Setup Node
              uses: actions/setup-node@v6
              with:
                  node-version: 20
                  cache: "npm"

            - name: 🏗 Setup Expo
              uses: expo/expo-github-action@v8
              with:
                  eas-version: latest
                  token: ${{ secrets.EXPO_TOKEN }}

            - name: 📦 Install dependencies
              run: npm ci

            - name: 🚀 Update Production with EAS
              run: npm run ota
